name: Draft Github Release

on:
  push:
    tags:
      - '**'

jobs:
  run-ci:
    uses: Jikoo/OpenInv/.github/workflows/ci.yml@master
  draft-release:
    needs: [ run-ci ]
    runs-on: ubuntu-latest
    steps:
      # Fetch all history - used to assemble changelog.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Release Variables
        run: bash ./scripts/set_release_env.sh

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Package resource pack
        run: |-
          pushd resource-pack
          zip -r ../dist/openinv-legibility-pack.zip .
          popd

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSIONED_NAME }}
          body: ${{ env.GENERATED_CHANGELOG }}
          draft: true
          prerelease: false
          files: ./dist/**
