name: Draft Github Release

on:
  push:
    tags:
      - '**'

jobs:
  run-ci:
    uses: Jikoo/OpenInv/.github/workflows/ci.yml@master
  draft-release:
    needs: [ run-ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: OpenInv ${{ env.VERSIONED_NAME }}
          body: |-
            ## Supported server versions
            **Paper:** TODO VERSION, 1.21.4, 1.21.3, 1.21.1
            **Spigot:** TODO VERSION
            
            TODO HELLO HUMAN, PRESS THE GENERATE CHANGELOG BUTTON PLEASE.
          draft: true
          prerelease: false
          files: ./dist/**
